name: 

on:
  push:
    branches:
      - main

Jobs:
  deploy:
    runs-on ubuntu-latest 
    
    staps: 
    - name: checkout
      uses: actions/checkout@v4

    -name:instalar Node.js
    uses: action/ setup-node@v4 
    with:
      node-version: 20
 
   - name: Instalar as dependências
     run: npm install
     working-directory: ./app
 
   - name: Adicionar os envs
     env:
      DB_HOST= ${{ secrets.DB_HOST }}
      DB_USER= ${{ secrets.DB_USER }}
      DB_PASSWORD= ${{ secrets.DB_PASSWORD }}
      APP_VERSION= ${{ secrets.APP_VERSION }}
      ENVIRONMENT= ${{ secrets.ENVIRONMENT }

      run: |
       timeout 10s npm start 
      working-directory: ./app 

    - name: Exeibir secrets mascarados 
      run:|
      echo "DB_HOST"=${{secets.DB_HOST}}  
      echo "DB_USER"=${{secets.DB_user}}  
      echo "APP_VERSION"=${{secets.APP_VERSION}}  
      echo "ENVIRONMENT"=${{secets.ENVIRONMENT}}  
       
       - name: Pipeline finalizada
         run: echo "Deploy execultado com sucesso

